### ISSUE TITLE
Move relationship graph below names & occupations

### ISSUE THREAD

**Issue by nathangibson** [usaybia/srophe#9]
For person detail pages this used to be below names & occupations, now it is on top. (Actually I kind of like it, but better wait until we do some more tweaking to it.)

#1

**Comment by wsalesky** [comment]
@nathangibson it is actually quite complicated to move it down because of the new architecture, which essentially renders the full TEI page via xslt and the more dynamic code in xquery, mixing them requires multiple calls to the xslt transformation. So if possible I would like to keep as is, or move the vis to the side bar.

**Comment by nathangibson** [comment]
@wsalesky OK, I can live with that. At the moment some things are slightly disorienting but it just means we should prioritize some of the overdue tweaks to the visualizations and person detail pages. But I think it is deployable as is. 

Is getting rid of the gray boxes for "Identity" and "Works Cited" intentional?

**Comment by wsalesky** [comment]
Yes, it is intentional, if you prefer it we can put them back.
-Winona

**Comment by nathangibson** [comment]
No problem, we can leave it and see what happens with the redesign.
